// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  The running application version, as declared in `tauri.conf.json`. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Today's date from the app clock (financial dates never come from the
	 *  browser).
	 */
	today: () => typedError<string, IpcError>(__TAURI_INVOKE("today")),
	/**  All accounts, open and closed, in display order. */
	accountList: () => typedError<Account[], IpcError>(__TAURI_INVOKE("account_list")),
	/**  Current and ending balance of every account (ACCT-230). */
	accountBalances: () => typedError<AccountBalance[], IpcError>(__TAURI_INVOKE("account_balances")),
	/**
	 *  A new account's fields with the type's defaults: group, tax treatment,
	 *  investment or other-asset settings (ACCT-030, ACCT-240).
	 */
	accountDefaults: (name: string, accountType: AccountType) => __TAURI_INVOKE<AccountFields>("account_defaults", { name, accountType }),
	/**  An account number reduced to its last four characters (ACCT-150). */
	accountNumberMasked: (number: string) => __TAURI_INVOKE<string>("account_number_masked", { number }),
	accountCreate: (fields: AccountFields) => typedError<Account, IpcError>(__TAURI_INVOKE("account_create", { fields })),
	/**  The account type cannot change after creation. */
	accountUpdate: (id: AccountId, fields: AccountFields) => typedError<Account, IpcError>(__TAURI_INVOKE("account_update", { id, fields })),
	/**
	 *  Close as of `date` (ACCT-210). A non-zero balance fails with
	 *  `confirmation_required` until `confirmed` is true.
	 */
	accountClose: (id: AccountId, date: string, confirmed: boolean) => typedError<Account, IpcError>(__TAURI_INVOKE("account_close", { id, date, confirmed })),
	accountReopen: (id: AccountId) => typedError<Account, IpcError>(__TAURI_INVOKE("account_reopen", { id })),
	/**  Only an account with no transactions can be deleted (ACCT-220). */
	accountDelete: (id: AccountId) => typedError<null, IpcError>(__TAURI_INVOKE("account_delete", { id })),
	/**  All categories, parents before children. */
	categoryList: () => typedError<Category[], IpcError>(__TAURI_INVOKE("category_list")),
	categoryCreate: (fields: CategoryFields) => typedError<Category, IpcError>(__TAURI_INVOKE("category_create", { fields })),
	/**
	 *  The category at a `Parent:Child` path, created (with any missing
	 *  parents) if it does not exist. For entering a new category inline.
	 */
	categoryCreatePath: (path: string, kind: CategoryKind) => typedError<Category, IpcError>(__TAURI_INVOKE("category_create_path", { path, kind })),
	/**  Built-in categories cannot be changed (CAT-060). */
	categoryUpdate: (id: CategoryId, fields: CategoryFields) => typedError<Category, IpcError>(__TAURI_INVOKE("category_update", { id, fields })),
	/**  Only an unused category can be deleted (CAT-030); hide it otherwise. */
	categoryDelete: (id: CategoryId) => typedError<null, IpcError>(__TAURI_INVOKE("category_delete", { id })),
	/**
	 *  Move everything from `source` to `target`, then remove `source`
	 *  (CAT-020).
	 */
	categoryMerge: (source: CategoryId, target: CategoryId) => typedError<Merged, IpcError>(__TAURI_INVOKE("category_merge", { source, target })),
	payeeList: () => typedError<Payee[], IpcError>(__TAURI_INVOKE("payee_list")),
	/**
	 *  Visible payees starting with `prefix`, ignoring case (PAY-020
	 *  QuickFill). Each carries its memorized defaults.
	 */
	payeeSearch: (prefix: string, limit: number) => typedError<Payee[], IpcError>(__TAURI_INVOKE("payee_search", { prefix, limit })),
	/**  Change a payee's name, memorized defaults, or visibility. */
	payeeUpdate: (id: PayeeId, fields: PayeeFields) => typedError<Payee, IpcError>(__TAURI_INVOKE("payee_update", { id, fields })),
	/**  Only an unused payee can be deleted (PAY-030); hide it otherwise. */
	payeeDelete: (id: PayeeId) => typedError<null, IpcError>(__TAURI_INVOKE("payee_delete", { id })),
	/**
	 *  Move everything from `source` to `target`, then remove `source`
	 *  (PAY-030).
	 */
	payeeMerge: (source: PayeeId, target: PayeeId) => typedError<Merged, IpcError>(__TAURI_INVOKE("payee_merge", { source, target })),
	tagList: () => typedError<Tag[], IpcError>(__TAURI_INVOKE("tag_list")),
	tagCreate: (fields: TagFields) => typedError<Tag, IpcError>(__TAURI_INVOKE("tag_create", { fields })),
	tagUpdate: (id: TagId, fields: TagFields) => typedError<Tag, IpcError>(__TAURI_INVOKE("tag_update", { id, fields })),
	/**  Only an unused tag can be deleted (TAG-020); hide it otherwise. */
	tagDelete: (id: TagId) => typedError<null, IpcError>(__TAURI_INVOKE("tag_delete", { id })),
	/**
	 *  Move everything from `source` to `target`, then remove `source`
	 *  (TAG-020).
	 */
	tagMerge: (source: TagId, target: TagId) => typedError<Merged, IpcError>(__TAURI_INVOKE("tag_merge", { source, target })),
	/**
	 *  Register rows for an account with filters, sort, and paging (REG-040).
	 *  The running balance is always the true one in date order (REG-020).
	 */
	registerQuery: (query: RegisterQuery) => typedError<RegisterPage, IpcError>(__TAURI_INVOKE("register_query", { query })),
	/**  Footer figures: current, cleared, ending, available credit (REG-060). */
	registerSummary: (account: AccountId) => typedError<RegisterSummary, IpcError>(__TAURI_INVOKE("register_summary", { account })),
	/**
	 *  Transactions matching some text or amount, in any account or one
	 *  (navigation bar search). Newest first, capped by `limit`.
	 */
	searchTransactions: (query: SearchQuery) => typedError<SearchPage, IpcError>(__TAURI_INVOKE("search_transactions", { query })),
	/**  A transaction as `account`'s register shows it, for editing. */
	entryGet: (txn: TxnId, account: AccountId) => typedError<Entry, IpcError>(__TAURI_INVOKE("entry_get", { txn, account })),
	/**
	 *  Save a new transaction. `payee_name`, when given, is looked up (or
	 *  created) in the same transaction and replaces `entry.payee`; an empty
	 *  name clears the payee. A first-time payee learns its defaults
	 *  (PAY-020). Returns the new transaction ID.
	 */
	entryCreate: (entry: Entry, payeeName: string | null) => typedError<TxnId, IpcError>(__TAURI_INVOKE("entry_create", { entry, payeeName })),
	/**
	 *  Replace a transaction (TXN-030: from either side of a transfer);
	 *  `payee_name` works as in [`entry_create`]. A reconciled one fails with
	 *  `confirmation_required` until `confirmed`.
	 */
	entryUpdate: (txn: TxnId, entry: Entry, payeeName: string | null, confirmed: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("entry_update", { txn, entry, payeeName, confirmed })),
	txnVoid: (txn: TxnId, confirmed: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("txn_void", { txn, confirmed })),
	txnDelete: (txn: TxnId, confirmed: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("txn_delete", { txn, confirmed })),
	/**  Mark the posting to `account` unmarked or cleared (the Clr column). */
	txnSetCleared: (txn: TxnId, account: AccountId, cleared: Cleared, confirmed: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("txn_set_cleared", { txn, account, cleared, confirmed })),
	/**
	 *  `total` minus the sum of `parts`: the unassigned amount of a split
	 *  (TXN-020). The UI does no money arithmetic, so it asks here.
	 */
	splitRemainder: (total: string, parts: string[]) => typedError<string, IpcError>(__TAURI_INVOKE("split_remainder", { total, parts })),
	/**  What changed, when, and from where, for one record (AUD-020). */
	auditHistory: (entity: AuditEntity, id: number) => typedError<AuditEntry[], IpcError>(__TAURI_INVOKE("audit_history", { entity, id })),
	/**  Run the integrity check (INT-030). */
	integrityCheck: () => typedError<IntegrityReport, IpcError>(__TAURI_INVOKE("integrity_check")),
	/**
	 *  Fill an empty book with about three years of synthetic data ending
	 *  three weeks from today, so the register shows the today line. Refuses a
	 *  book that already has accounts.
	 */
	sampleDataLoad: (seed: number) => typedError<SampleSummary, IpcError>(__TAURI_INVOKE("sample_data_load", { seed })),
	/**  The Scheduled Transactions list, next due first (REC-300). */
	scheduleList: () => typedError<ScheduleRow[], IpcError>(__TAURI_INVOKE("schedule_list")),
	scheduleGet: (id: ScheduleId) => typedError<Schedule, IpcError>(__TAURI_INVOKE("schedule_get", { id })),
	/**  Create a schedule (REC-100). `payee_name` works as in `entry_create`. */
	scheduleCreate: (fields: ScheduleFields, payeeName: string | null) => typedError<Schedule, IpcError>(__TAURI_INVOKE("schedule_create", { fields, payeeName })),
	/**  Edit a schedule for this and all future occurrences (REC-120). */
	scheduleUpdate: (id: ScheduleId, fields: ScheduleFields, payeeName: string | null) => typedError<Schedule, IpcError>(__TAURI_INVOKE("schedule_update", { id, fields, payeeName })),
	scheduleDelete: (id: ScheduleId) => typedError<null, IpcError>(__TAURI_INVOKE("schedule_delete", { id })),
	/**
	 *  A schedule prefilled from a transaction, for "Schedule this" (REC-140).
	 *  Nothing is saved; the UI shows it for editing, then calls
	 *  `schedule_create`.
	 */
	scheduleFromTxn: (txn: TxnId, account: AccountId) => typedError<ScheduleFields, IpcError>(__TAURI_INVOKE("schedule_from_txn", { txn, account })),
	/**
	 *  The entry an occurrence would become, for editing in the register
	 *  before it is entered (REC-110).
	 */
	schedulePrefill: (schedule: ScheduleId, due: string) => typedError<Entry, IpcError>(__TAURI_INVOKE("schedule_prefill", { schedule, due })),
	/**
	 *  Enter an occurrence as a transaction (REC-110). `edits.entry` is the
	 *  transaction as the user edited it; `payee_name` replaces its payee as in
	 *  `entry_create`. Without an entry, an estimated amount fails with
	 *  `confirmation_required` until `confirmed` or an amount is given.
	 */
	scheduleEnter: (schedule: ScheduleId, due: string, edits: EnterEdits, payeeName: string | null, confirmed: boolean) => typedError<Entered, IpcError>(__TAURI_INVOKE("schedule_enter", { schedule, due, edits, payeeName, confirmed })),
	scheduleSkip: (schedule: ScheduleId, due: string) => typedError<null, IpcError>(__TAURI_INVOKE("schedule_skip", { schedule, due })),
	/**
	 *  "Edit this occurrence only" (REC-110): a one-time date and/or amount;
	 *  both `null` clears it.
	 */
	scheduleOverride: (schedule: ScheduleId, due: string, date: string | null, amount: string | null) => typedError<{
	id: number,
	schedule: ScheduleId,
	/**  Nominal date. */
	due_date: string,
	status: OccurrenceStatus,
	override_date: string | null,
	/**  The main account's amount, when changed for this occurrence only. */
	override_amount: string | null,
	txn: TxnId | null,
	needs_review: boolean,
} | null, IpcError>(__TAURI_INVOKE("schedule_override", { schedule, due, date, amount })),
	/**
	 *  Due and overdue occurrences, within each schedule's reminder window
	 *  (REC-130).
	 */
	scheduleDueList: () => typedError<OccurrenceView[], IpcError>(__TAURI_INVOKE("schedule_due_list")),
	/**
	 *  Enter what auto-entry schedules owe up to today, including occurrences
	 *  missed while the app was closed (REC-070). Call once at startup, before
	 *  the due list.
	 */
	scheduleAutoEnter: () => typedError<AutoEnterReport, IpcError>(__TAURI_INVOKE("schedule_auto_enter")),
	/**  Auto-entered occurrences awaiting review. */
	scheduleReviewList: () => typedError<OccurrenceView[], IpcError>(__TAURI_INVOKE("schedule_review_list")),
	/**
	 *  Mark auto-entered occurrences (schedule and nominal date, as in
	 *  `schedule_review_list`) as reviewed.
	 */
	scheduleReviewDismiss: (items: ([ScheduleId, string])[]) => typedError<number, IpcError>(__TAURI_INVOKE("schedule_review_dismiss", { items })),
	/**  Calendar occurrences dated `from..=to` (CAL-010, CAL-020, CAL-040). */
	calendarOccurrences: (from: string, to: string, accounts: AccountId[] | null, includeDone: boolean) => typedError<OccurrenceView[], IpcError>(__TAURI_INVOKE("calendar_occurrences", { from, to, accounts, includeDone })),
	/**  Projected end-of-day balance of an account (CAL-050). */
	calendarProjection: (account: AccountId, from: string, to: string) => typedError<DayBalance[], IpcError>(__TAURI_INVOKE("calendar_projection", { account, from, to })),
	/**
	 *  The account's in-progress reconciliation, if any, to resume it
	 *  (RCN-050).
	 */
	reconcileOpen: (account: AccountId) => typedError<{
	id: ReconciliationId,
	account: AccountId,
	statement_date: string,
	/**
	 *  The prior statement's ending balance when the session started
	 *  (RCN-030); the reconciled postings' total if there was none.
	 */
	opening_balance: string,
	/**  Ending balance on the statement, statement sign. */
	statement_balance: string,
	status: ReconStatus,
	started_at: string,
	finished_at: string | null,
} | null, IpcError>(__TAURI_INVOKE("reconcile_open", { account })),
	/**
	 *  Do the account's reconciled postings still add up to its last
	 *  statement, and if not, which reconciled transactions changed (RCN-030)?
	 *  Shown before the statement is entered.
	 */
	reconcileOpeningCheck: (account: AccountId) => typedError<OpeningCheck, IpcError>(__TAURI_INVOKE("reconcile_opening_check", { account })),
	/**
	 *  Start a reconciliation (RCN-020 step 1). Interest and a service charge,
	 *  when given, are entered as transactions. Reconcile commands take and
	 *  return amounts in statement sign: a credit card balance owed is
	 *  positive.
	 */
	reconcileStart: (input: StartInput) => typedError<Reconciliation, IpcError>(__TAURI_INVOKE("reconcile_start", { input })),
	/**  The session's items, checked totals, and difference (RCN-020 step 3). */
	reconcileSession: (id: ReconciliationId) => typedError<Session, IpcError>(__TAURI_INVOKE("reconcile_session", { id })),
	/**  Correct the statement date or ending balance of a session in progress. */
	reconcileUpdate: (id: ReconciliationId, statementDate: string, statementBalance: string) => typedError<Session, IpcError>(__TAURI_INVOKE("reconcile_update", { id, statementDate, statementBalance })),
	/**  Check or uncheck items; returns the session as it now stands. */
	reconcileCheck: (id: ReconciliationId, txns: TxnId[], checked: boolean) => typedError<Session, IpcError>(__TAURI_INVOKE("reconcile_check", { id, txns, checked })),
	/**
	 *  Balance Adjustment for the current difference (RCN-040). Fails with
	 *  `confirmation_required` until `confirmed`; returns the session.
	 */
	reconcileAdjust: (id: ReconciliationId, confirmed: boolean) => typedError<Session, IpcError>(__TAURI_INVOKE("reconcile_adjust", { id, confirmed })),
	/**  Finish (RCN-020 step 4): only with a zero difference. */
	reconcileFinish: (id: ReconciliationId) => typedError<Reconciliation, IpcError>(__TAURI_INVOKE("reconcile_finish", { id })),
	/**  Give up a session in progress; it stays in the history. */
	reconcileAbandon: (id: ReconciliationId) => typedError<Reconciliation, IpcError>(__TAURI_INVOKE("reconcile_abandon", { id })),
	/**  An account's reconciliations, newest first (RCN-060). */
	reconcileHistory: (account: AccountId) => typedError<HistoryRow[], IpcError>(__TAURI_INVOKE("reconcile_history", { account })),
	/**  What one reconciliation reconciled (RCN-060). */
	reconcileHistoryItems: (id: ReconciliationId) => typedError<Item[], IpcError>(__TAURI_INVOKE("reconcile_history_items", { id })),
	/**  Every security, hidden ones included, by name. */
	securityList: () => typedError<Security[], IpcError>(__TAURI_INVOKE("security_list")),
	/**  A new security's fields with the type's default asset class. */
	securityDefaults: (name: string, securityType: SecurityType) => __TAURI_INVOKE<SecurityFields>("security_defaults", { name, securityType }),
	securityCreate: (fields: SecurityFields) => typedError<Security, IpcError>(__TAURI_INVOKE("security_create", { fields })),
	securityUpdate: (id: SecurityId, fields: SecurityFields) => typedError<Security, IpcError>(__TAURI_INVOKE("security_update", { id, fields })),
	/**  Only a security no transaction uses can be deleted (SEC-040). */
	securityDelete: (id: SecurityId) => typedError<null, IpcError>(__TAURI_INVOKE("security_delete", { id })),
	/**  A security's prices, newest first. */
	priceList: (security: SecurityId) => typedError<PricePoint[], IpcError>(__TAURI_INVOKE("price_list", { security })),
	/**  Enter or replace the closing price on a date (PRC-020). */
	priceSet: (security: SecurityId, date: string, price: string) => typedError<null, IpcError>(__TAURI_INVOKE("price_set", { security, date, price })),
	priceDelete: (security: SecurityId, date: string) => typedError<null, IpcError>(__TAURI_INVOKE("price_delete", { security, date })),
	/**  Check a price CSV without writing anything (PRC-030). */
	priceImportPreview: (text: string) => typedError<PriceImportPreview, IpcError>(__TAURI_INVOKE("price_import_preview", { text })),
	/**  Import a price CSV, all or nothing. Returns the number of prices. */
	priceImport: (text: string) => typedError<number, IpcError>(__TAURI_INVOKE("price_import", { text })),
	/**  An investment account's register (INV-030). */
	invRegister: (account: AccountId) => typedError<InvRegister, IpcError>(__TAURI_INVOKE("inv_register", { account })),
	invGet: (txn: TxnId) => typedError<InvTxn, IpcError>(__TAURI_INVOKE("inv_get", { txn })),
	/**  The stored transaction as an input, to edit and send back. */
	invInput: (txn: TxnId) => typedError<InvInput, IpcError>(__TAURI_INVOKE("inv_input", { txn })),
	invCreate: (input: InvInput) => typedError<TxnId, IpcError>(__TAURI_INVOKE("inv_create", { input })),
	/**
	 *  Replace an investment transaction; a reconciled cash posting fails
	 *  with `confirmation_required` until `confirmed`.
	 */
	invUpdate: (txn: TxnId, input: InvInput, confirmed: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("inv_update", { txn, input, confirmed })),
	invDelete: (txn: TxnId, confirmed: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("inv_delete", { txn, confirmed })),
	/**
	 *  Shares × price ± commission for the entry form; the UI does no money
	 *  arithmetic.
	 */
	invTradeAmount: (action: InvAction, quantity: string, price: string, commission: string) => typedError<string, IpcError>(__TAURI_INVOKE("inv_trade_amount", { action, quantity, price, commission })),
	/**  Holdings on `as_of` (today when left out) (POS-010). */
	invHoldings: (account: AccountId, asOf: string | null) => typedError<Holdings, IpcError>(__TAURI_INVOKE("inv_holdings", { account, asOf })),
	/**
	 *  Open lots on `as_of` (today when left out), one security or all
	 *  (LOT-150; the lot picker for specific identification).
	 */
	invLots: (account: AccountId, security: number | null, asOf: string | null) => typedError<LotView[], IpcError>(__TAURI_INVOKE("inv_lots", { account, security, asOf })),
	/**  Realized gains in one account or all, between two dates (LOT-040). */
	invGains: (account: number | null, from: string | null, to: string | null) => typedError<RealizedGain[], IpcError>(__TAURI_INVOKE("inv_gains", { account, from, to })),
	invIncome: (account: AccountId, from: string | null, to: string | null) => typedError<IncomeReport, IpcError>(__TAURI_INVOKE("inv_income", { account, from, to })),
	/**  Simple performance as of today (POS-030). */
	invPerformance: (account: AccountId) => typedError<Performance, IpcError>(__TAURI_INVOKE("inv_performance", { account })),
	/**
	 *  Asset allocation today across `accounts` (every open investment
	 *  account when empty) (POS-020).
	 */
	invAllocation: (accounts: AccountId[]) => typedError<Allocation, IpcError>(__TAURI_INVOKE("inv_allocation", { accounts })),
	/**  Check a lot-seeding CSV without writing anything. */
	lotSeedPreview: (text: string, date: string) => typedError<SeedPreview, IpcError>(__TAURI_INVOKE("lot_seed_preview", { text, date })),
	/**
	 *  Seed lots from a CSV as one import batch, all or nothing. Returns the
	 *  number of lots created.
	 */
	lotSeed: (fileName: string, text: string, date: string) => typedError<number, IpcError>(__TAURI_INVOKE("lot_seed", { fileName, text, date })),
};

/* Types */
/**  A stored account. */
export type Account = {
	id: AccountId,
	status: AccountStatus,
	closed_date: string | null,
	created_at: string,
} & AccountFields;

/**  One account's figures for the account list (UI-010). */
export type AccountBalance = {
	account: AccountId,
	/**  Postings dated today or earlier. */
	current: string,
	/**  All postings, including future-dated ones. */
	ending: string,
};

/**
 *  Editable attributes of an account (ACCT-100 … ACCT-160). Used to
 *  create and to update.
 */
export type AccountFields = {
	name: string,
	account_type: AccountType,
	group: AccountGroup,
	tax_treatment: TaxTreatment,
	description: string,
	institution: string,
	account_number: string,
	contact_phone: string,
	home_url: string,
	notes: string,
	opening_date: string | null,
	show_in_bar: boolean,
	show_in_list: boolean,
	sort_order: number,
	/**  Checking, Savings, Money Market only. */
	interest_rate: string | null,
	/**  Credit Card only. */
	credit_limit: string | null,
	/**  Required for investment types; absent otherwise. */
	investment: InvestmentSettings | null,
	/**  Required for Other Asset; absent otherwise. */
	other_asset: OtherAssetSettings | null,
};

/**  Account list groups (ACCT-240). */
export type AccountGroup = "banking" | "credit" | "investments" | "retirement" | "assets" | "liabilities";

/**  Row ID of an account. */
export type AccountId = number;

/**  Open or closed (ACCT-210). */
export type AccountStatus = "open" | "closed";

/**  Account types (ACCT-010, ACCT-020; D-100). */
export type AccountType = "checking" | "savings" | "credit_card" | "cash" | "money_market" | "brokerage" | "traditional_ira" | "roth_ira" | "hsa" | 
/**  401(k)/403(b). */
"retirement_401k" | "other_asset" | "other_liability" | 
/**  Loan or mortgage; balance tracking only in 1.0. */
"loan";

/**  A split or return of capital on one lot (LOT-120, LOT-130). */
export type Adjustment = {
	lot: LotId,
	kind: AdjustmentKind,
	quantity_delta: string,
	basis_delta: string,
};

/**  A change to an open lot that is not a disposal. */
export type AdjustmentKind = "split" | "return_of_capital";

export type Allocation = {
	as_of: string,
	accounts: AccountId[],
	rows: AllocationRow[],
	total: string,
	/**  Holdings with no price are left out. */
	missing_prices: boolean,
};

export type AllocationRow = {
	asset_class: AssetClass,
	market_value: string,
	/**  Share of the total, percent with two decimals. */
	percent: string,
};

/**
 *  Fixed amounts enter as scheduled; estimated ones are confirmed on
 *  entry (REC-060).
 */
export type AmountType = "fixed" | "estimated";

/**  Asset class for allocation (SEC-010, POS-020). */
export type AssetClass = "us_equity" | "intl_equity" | "bond" | "cash" | "real_estate" | "commodity" | "other";

/**  Kind of an Other Asset account (ACCT-140). */
export type AssetSubtype = "house" | "vehicle" | "other";

/**  What happened. */
export type AuditAction = "create" | "update" | "void" | "delete" | "merge" | "close" | "reopen" | "rollback";

/**  What kind of record an audit entry describes. */
export type AuditEntity = "account" | "category" | "payee" | "tag" | "txn" | "security" | "price" | "lot" | "schedule" | "reconciliation" | "import_batch" | "saved_report";

/**  An audit entry with its changes spelled out. */
export type AuditEntry = {
	id: number,
	at: string,
	action: AuditAction,
	/**  `ui`, `import`, `scheduler`, or `system`. */
	origin: string,
	import_batch_id: number | null,
	/**
	 *  A create lists every field (`before` empty); a delete lists every
	 *  field (`after` empty); anything else lists only differing fields.
	 */
	changes: FieldChange[],
};

/**  An occurrence auto-entry could not enter. */
export type AutoEnterFailure = {
	schedule: ScheduleId,
	nominal: string,
	reason: string,
};

/**  What auto-entry did. */
export type AutoEnterReport = {
	entered: Entered[],
	/**
	 *  Schedules stopped by an error (a closed account, say). They stay in
	 *  the due list.
	 */
	failed: AutoEnterFailure[],
};

/**  Where an investment account's cash lives (INV-300). */
export type CashMode = "internal" | "linked";

/**  A stored category. */
export type Category = {
	id: CategoryId,
	/**
	 *  Set for built-in categories, which can't be renamed, moved, or
	 *  deleted.
	 */
	system: SystemCategory | null,
	created_at: string,
} & CategoryFields;

/**  Editable attributes of a category. */
export type CategoryFields = {
	parent: CategoryId | null,
	kind: CategoryKind,
	name: string,
	/**  CAT-040 flags. */
	tax_related: boolean,
	tithable: boolean,
	giving: boolean,
	/**  CAT-030: hide instead of delete. */
	hidden: boolean,
};

/**  Row ID of a category. */
export type CategoryId = number;

/**  Category kind (CAT-010). `Equity` is system-only (opening balances). */
export type CategoryKind = "income" | "expense" | "equity";

/**  A reconciled transaction changed since the last statement (RCN-030). */
export type ChangedTxn = {
	txn_id: TxnId,
	date: string | null,
	/**  Its reconciled amount on this account at the last statement. */
	was: string,
	/**  Its reconciled amount now: zero if deleted, voided, or unreconciled. */
	now: string,
	/**  The latest change: `create`, `update`, `void`, or `delete`. */
	action: AuditAction,
};

/**  Which invariant failed. */
export type Check = 
/**  `PRAGMA integrity_check` reported a problem. */
"sqlite_integrity" | 
/**  `PRAGMA foreign_key_check` found a dangling reference. */
"foreign_keys" | 
/**  A transaction's postings do not sum to zero. */
"unbalanced" | 
/**  A transaction has no posting to an account, so no register shows it. */
"no_account_posting" | 
/**  One transaction posts to the same account twice (not a holding). */
"duplicate_account_posting" | 
/**  A voided transaction has a non-zero posting. */
"void_with_amount" | 
/**  A closed account has a posting dated after its closing date. */
"posting_after_close" | 
/**  A posting links to a reconciliation that is not finished. */
"unfinished_reconciliation" | 
/**
 *  An account's reconciled postings no longer add up to its last
 *  finished statement's ending balance.
 */
"reconciled_balance_mismatch" | 
/**  Following parents from a category leads back to it. */
"category_cycle" | 
/**  A subcategory's kind differs from its parent's. */
"category_kind_mismatch" | 
/**
 *  A lot's open shares or basis is below zero, or it has basis left
 *  with no shares.
 */
"lot_overdrawn" | 
/**
 *  A holding's shares from its transactions (bought, sold, split,
 *  moved) differ from the sum of its open lots (POS-050).
 */
"share_balance_mismatch" | 
/**
 *  A holding's cost basis in the ledger (its postings) differs from
 *  the sum of its open lots' basis (INT-030 lot basis totals).
 */
"lot_basis_mismatch" | 
/**
 *  A transaction's shares differ from the lots it created or the
 *  shares it took out of lots.
 */
"lot_quantity_mismatch";

/**  Cleared status of an account posting (glossary; RCN-020). */
export type Cleared = "unmarked" | "cleared" | 
/**  Set only by reconciliation (Phase 5) or an import (MIG-090). */
"reconciled";

/**  What sits on the other side of a register row. */
export type Counterpart = 
/**  No other posting (a zero-amount entry). */
{ kind: "none" } | { kind: "category"; id: CategoryId } | { kind: "transfer"; id: AccountId } | 
/**  More than one other posting (REG-050 "--Split--"). */
{ kind: "split" };

/**  Projected balance at the end of a day (CAL-050). */
export type DayBalance = {
	date: string,
	balance: string,
};

/**  Shares leaving a lot. A sale is a realized gain record (LOT-040). */
export type Disposal = {
	lot: LotId,
	kind: DisposalKind,
	quantity: string,
	basis: string,
	proceeds: string | null,
	gain: string | null,
	term: Term | null,
};

/**  Why shares left a lot. */
export type DisposalKind = "sale" | "transfer_out" | "removed";

/**  When a schedule stops (REC-030). */
export type End = { kind: "never" } | 
/**  Occurrences dated after `date` do not happen. */
{ kind: "on_date"; date: string } | 
/**
 *  `count` occurrences remain ("# left"); entering or skipping one
 *  uses it up.
 */
{ kind: "after_count"; count: number };

/**  Changes the user makes while entering an occurrence (REC-110). */
export type EnterEdits = {
	/**  Enter it on this date instead. */
	date: string | null,
	/**
	 *  The main account's amount, for a schedule with a single line. Split
	 *  schedules are edited in the register after entering.
	 */
	amount: string | null,
	/**
	 *  The whole transaction as the user edited it in the register (any
	 *  field, splits included). When given, `date` and `amount` are
	 *  ignored, and an estimated amount counts as confirmed. Its account
	 *  must be the schedule's.
	 */
	entry: Entry | null,
};

/**  An occurrence that became a transaction. */
export type Entered = {
	schedule: ScheduleId,
	nominal: string,
	txn: TxnId,
	date: string,
};

/**  A transaction as one account's register shows it. */
export type Entry = {
	account: AccountId,
	date: string,
	payee: PayeeId | null,
	check_num: string,
	memo: string,
	notes: string,
	/**
	 *  This account's posting: − payment or charge, + deposit (for a
	 *  liability account, − is a charge and + a payment).
	 */
	amount: string,
	cleared: Cleared,
	/**  Transaction-level tags (TAG-010), stored on this account's posting. */
	tags: TagId[],
	/**  One line for a simple transaction; several for a split. */
	lines: EntryLine[],
};

/**
 *  One line on the other side of an entry: a category or a transfer
 *  account (TXN-020).
 */
export type EntryLine = {
	target: Target,
	/**  Same sign as [`Entry::amount`]; the line's posting is minus this. */
	amount: string,
	memo: string,
	/**  The other account's cleared status (transfer lines only). */
	cleared: Cleared,
	tags: TagId[],
};

/**
 *  Remind: the user enters each occurrence. Auto: entered on the due
 *  date and flagged for review (REC-070).
 */
export type EntryMode = "remind" | "auto";

export type ErrorKind = 
/**  The request broke a domain rule; show the message. */
"invalid" | "not_found" | 
/**  The row is used elsewhere; hide or close it instead. */
"in_use" | 
/**  Repeat the call with `confirmed = true` after the user agrees. */
"confirmation_required" | 
/**  Malformed input (a bad amount or date). */
"bad_input" | 
/**  Anything else: a database or internal failure. */
"internal";

/**
 *  One field that differs between the before and after snapshots.
 *  Nested values use paths like `postings[1].amount`. `None` means the
 *  field did not exist on that side.
 */
export type FieldChange = {
	path: string,
	before: string | null,
	after: string | null,
};

/**
 *  How often a schedule repeats (REC-020). Quarterly and twice a year
 *  are `Monthly` with interval 3 and 6.
 */
export type Frequency = "once" | "daily" | "weekly" | "twice_monthly" | "monthly" | "monthly_last_day" | "monthly_nth_weekday" | "yearly";

/**  One row of the reconciliation history (RCN-060). */
export type HistoryRow = {
	reconciliation: Reconciliation,
	/**  Postings it reconciled that are still reconciled. */
	item_count: number,
	items_total: string,
};

/**  An investment account's holdings (POS-010, POS-040 Holdings tab). */
export type Holdings = {
	account: AccountId,
	as_of: string,
	positions: Position[],
	/**  `None` with linked cash. */
	cash: string | null,
	/**  Σ cost basis of the positions. */
	basis: string,
	/**  Σ market value of the positions that have a price. */
	market_value: string,
	/**  Market value plus cash. */
	total_value: string,
	/**  Σ unrealized gain of the positions that have a price. */
	unrealized: string,
	/**  Some position has no price, so the totals leave it out. */
	missing_prices: boolean,
	stale_prices: boolean,
};

/**  Income by security, with totals. */
export type IncomeReport = {
	rows: IncomeRow[],
	total: IncomeRow,
};

/**
 *  Investment income from one security (or none: interest and other
 *  income not tied to a security).
 */
export type IncomeRow = {
	security: SecurityId | null,
	security_label: string,
	/**  Cash and reinvested dividends. */
	dividends: string,
	interest: string,
	cg_short: string,
	cg_long: string,
	/**  Miscellaneous income. */
	other: string,
	total: string,
};

/**  Result of an integrity check. */
export type IntegrityReport = {
	issues: Issue[],
};

/**  Investment transaction types (INV-010). */
export type InvAction = "buy" | "sell" | "dividend" | "interest" | "reinvest_dividend" | "reinvest_cg_short" | "reinvest_cg_long" | "cg_dist_short" | "cg_dist_long" | "return_of_capital" | "split" | "transfer_shares" | "shares_added" | "shares_removed" | "cash_in" | "cash_out" | "fee" | "tax_withholding" | "misc_income" | "misc_expense";

/**
 *  An investment transaction to be written (INV-010, INV-020). Fields an
 *  action does not use must be left empty; the engine says which.
 */
export type InvInput = {
	account: AccountId,
	action: InvAction,
	/**  Trade date. */
	date: string,
	settle_date: string | null,
	security: SecurityId | null,
	quantity: string | null,
	price: string | null,
	/**  Buy and sell only. */
	commission: string,
	/**
	 *  Always positive; the engine gives it its sign. Buy: total cost
	 *  with commission. Sell: proceeds after commission. Reinvest: the
	 *  amount reinvested. Shares added: their cost basis. Otherwise the
	 *  amount paid or received. For buy, sell, and reinvest it may be
	 *  left out and is then shares × price (± commission).
	 */
	amount: string | null,
	split: SplitRatio | null,
	/**  Share transfers: the investment account receiving the shares. */
	to_account: AccountId | null,
	/**  Overrides the security's and account's lot selection method. */
	lot_method: LotMethod | null,
	/**  Specific identification: shares from each lot (LOT-100). */
	lots: LotPick[],
	/**
	 *  Shares added: the original acquisition date (MIG-120); the trade
	 *  date when left out.
	 */
	acquired: string | null,
	/**
	 *  Cash in/out: the other account or a category. Misc income or
	 *  expense: a category instead of the built-in one.
	 */
	counterpart: Target | null,
	memo: string,
};

/**  An investment account's register. */
export type InvRegister = {
	account: AccountId,
	rows: InvRegisterRow[],
	/**  Cash as of today; `None` with linked cash (INV-300). */
	cash: string | null,
	/**  Cash below zero is allowed but flagged (INV-310). */
	negative_cash: boolean,
	today: string,
};

/**  One row of an investment account's register. */
export type InvRegisterRow = {
	txn_id: TxnId,
	date: string,
	settle_date: string | null,
	action: InvAction,
	/**
	 *  For display: "Buy", "Reinvest Div", ... ("Transfer In" for shares
	 *  arriving from another account).
	 */
	action_label: string,
	security: SecurityId | null,
	/**  Ticker, or name if none. */
	security_label: string,
	quantity: string | null,
	price: string | null,
	commission: string,
	split: SplitRatio | null,
	/**
	 *  Cash in (+) or out (−) of the account's cash (or its linked cash
	 *  account); zero when none moves.
	 */
	amount: string,
	/**  Running cash balance, in date order; `None` with linked cash. */
	cash_balance: string | null,
	memo: string,
	/**  The cash posting's status; `None` when there is none. */
	cleared: Cleared | null,
	/**  The other account: share transfers, and cash in/out. */
	other_account: AccountId | null,
	/**  A category the cash came from or went to (cash in/out, misc). */
	other_category: CategoryId | null,
	/**  Shares arriving here from another account. */
	incoming: boolean,
	/**  Dated after today (REG-070). */
	future: boolean,
};

/**
 *  A stored investment transaction: the ledger transaction with its
 *  trade detail and lot records.
 */
export type InvTxn = {
	account: AccountId,
	action: InvAction,
	security: SecurityId | null,
	quantity: string | null,
	price: string | null,
	commission: string,
	split: SplitRatio | null,
	to_account: AccountId | null,
	lot_method: LotMethod | null,
	settle_date: string | null,
	/**
	 *  The cash posting, as the cash account sees it (+ in, − out);
	 *  zero when the action moves no cash.
	 */
	cash: string,
	lots: Lot[],
	disposals: Disposal[],
	adjustments: Adjustment[],
} & Txn;

/**  Settings only investment accounts have (ACCT-130, INV-300, D-50). */
export type InvestmentSettings = {
	subtype: string | null,
	cash_mode: CashMode,
	/**  Required when `cash_mode` is `Linked`. */
	linked_cash_account: AccountId | null,
	mmf_mode: MmfMode,
	default_lot_method: LotMethod,
};

/**
 *  Why a command failed, in a shape the UI can act on. `kind` picks the
 *  reaction (e.g. `confirmation_required` opens a confirm dialog);
 *  `message` is display text.
 */
export type IpcError = {
	kind: ErrorKind,
	message: string,
};

/**  One failed invariant on one record. */
export type Issue = {
	check: Check,
	/**  Table of the offending record (`txn`, `posting`, `category`, ...). */
	table: string,
	/**  Its row ID, when there is one. */
	id: number | null,
	detail: string,
};

/**  One posting the user can check off. */
export type Item = {
	txn_id: TxnId,
	date: string,
	check_num: string,
	payee_name: string,
	memo: string,
	/**
	 *  This account's posting, statement sign: on a credit card a charge
	 *  is positive and a payment negative.
	 */
	amount: string,
	checked: boolean,
};

/**  A lot as recorded at acquisition (LOT-010). */
export type Lot = {
	id: LotId,
	account: AccountId,
	security: SecurityId,
	acquired: string,
	quantity: string,
	basis: string,
	origin_txn: TxnId,
	/**  The lot it came from, for shares transferred in (LOT-140). */
	source_lot: LotId | null,
};

/**  Row ID of a lot. */
export type LotId = number;

/**
 *  Lot selection methods (LOT-100, LOT-110, D-60). The prototype
 *  engine implements `Fifo` and `Specific`; the others are stored so
 *  the schema doesn't change when they arrive.
 */
export type LotMethod = "fifo" | "specific" | "average" | 
/**  Highest cost first. */
"hifo" | 
/**
 *  Minimize tax: short-term losses, long-term losses, long-term
 *  gains (smallest first), short-term gains (smallest first).
 */
"min_tax";

/**  Shares to take from one lot (specific identification, LOT-100). */
export type LotPick = {
	lot: LotId,
	quantity: string,
};

/**  An open lot, valued (LOT-150). */
export type LotView = {
	security_label: string,
	open_quantity: string,
	open_basis: string,
	/**  Open basis ÷ open shares. */
	per_share: string | null,
	market_value: string | null,
	unrealized: string | null,
	/**  Holding period if sold on the valuation date. */
	term: Term,
} & Lot;

/**
 *  What a merge moved from the source to the target (CAT-020, PAY-030,
 *  TAG-020). Recorded as the `after` value of the merge's audit entry.
 */
export type Merged = {
	/**  ID of the surviving category, payee, or tag. */
	into: number,
	postings: number,
	txns: number,
	schedules: number,
	schedule_lines: number,
	payee_defaults: number,
	subcategories: number,
};

/**  How money market funds are held in an investment account (INV-050, D-50). */
export type MmfMode = 
/**  A security priced at $1.00. */
"security" | 
/**  Part of the account's cash balance. */
"cash";

/**  A stored occurrence row. */
export type Occurrence = {
	id: number,
	schedule: ScheduleId,
	/**  Nominal date. */
	due_date: string,
	status: OccurrenceStatus,
	override_date: string | null,
	/**  The main account's amount, when changed for this occurrence only. */
	override_amount: string | null,
	txn: TxnId | null,
	needs_review: boolean,
};

/**
 *  What became of an occurrence (REC-110). `Pending` rows carry a
 *  one-time override.
 */
export type OccurrenceStatus = "pending" | "entered" | "skipped";

/**  One occurrence as lists and the calendar show it. */
export type OccurrenceView = {
	schedule: ScheduleId,
	/**  Nominal date: identifies the occurrence. */
	nominal: string,
	/**  When it is due: weekend rule or one-time override applied. */
	date: string,
	/**  The main account's amount, override applied. */
	amount: string,
	status: OccurrenceStatus,
	account: AccountId,
	payee: PayeeId | null,
	estimated: boolean,
	mode: EntryMode,
	/**  A one-time date or amount is set. */
	overridden: boolean,
	/**  The transaction, once entered. */
	txn: TxnId | null,
	needs_review: boolean,
	/**  Pending and dated before today. */
	overdue: boolean,
	/**  Only the schedule's next occurrence can be entered or skipped. */
	actionable: boolean,
};

/**  Do the reconciled postings still add up to the last statement? */
export type OpeningCheck = {
	/**
	 *  The last finished statement's ending balance; the reconciled total
	 *  when there is none.
	 */
	expected: string,
	/**  Σ reconciled postings now. */
	actual: string,
	/**
	 *  Reconciled transactions changed since the last statement, when
	 *  `expected` and `actual` differ. May be empty: the gap can predate
	 *  the audit log (e.g. imported data).
	 */
	changed: ChangedTxn[],
	/**  `expected == actual`. */
	matches: boolean,
};

/**  Settings only Other Asset accounts have (ACCT-140). */
export type OtherAssetSettings = {
	subtype: AssetSubtype,
	linked_liability: AccountId | null,
};

/**  A stored payee. */
export type Payee = {
	id: PayeeId,
	created_at: string,
} & PayeeFields;

/**  Editable attributes of a payee, including memorized defaults (PAY-020). */
export type PayeeFields = {
	name: string,
	default_category: CategoryId | null,
	default_tag: TagId | null,
	default_memo: string,
	default_amount: string | null,
	hidden: boolean,
};

/**  Row ID of a payee. */
export type PayeeId = number;

/**
 *  Simple performance of one security in an account, or the account's
 *  total (`security` `None`).
 */
export type PerfRow = {
	security: SecurityId | null,
	security_label: string,
	/**  Open cost basis. */
	basis: string,
	market_value: string | null,
	unrealized: string | null,
	realized: string,
	income: string,
	/**  Unrealized + realized + income. */
	total_gain: string | null,
	/**
	 *  Total gain ÷ (open basis + basis of shares sold), in percent, two
	 *  decimals.
	 */
	total_return: string | null,
};

export type Performance = {
	account: AccountId,
	as_of: string,
	rows: PerfRow[],
	total: PerfRow,
};

/**  One security held in one account (POS-010). */
export type Position = {
	account: AccountId,
	security: SecurityId,
	name: string,
	ticker: string | null,
	security_type: SecurityType,
	asset_class: AssetClass,
	shares: string,
	basis: string,
	/**
	 *  Latest price on or before the valuation date; `None` if there is
	 *  none.
	 */
	price: string | null,
	/**  `None` for a money market fund valued at $1.00 without a price. */
	price_date: string | null,
	/**  The price is older than the stale threshold (PRC-050). */
	stale: boolean,
	market_value: string | null,
	unrealized: string | null,
};

/**  A stored posting. */
export type Posting = {
	id: PostingId,
	line_no: number,
	target: Target,
	amount: string,
	memo: string,
	cleared: Cleared,
	/**
	 *  The reconciliation that marked this posting reconciled; `None` for
	 *  imported reconciled status (MIG-090).
	 */
	reconciliation_id: number | null,
	/**  Sorted by ID. */
	tags: TagId[],
	/**
	 *  Investment accounts: the holding whose cost basis this posting
	 *  carries; `None` for cash and for every other account.
	 */
	security: SecurityId | null,
};

/**
 *  Row ID of a posting. Not stable across edits: an edit replaces a
 *  transaction's postings.
 */
export type PostingId = number;

/**  What an import would do (MIG-050 style preview). */
export type PriceImportPreview = {
	rows: PriceImportRow[],
	good: number,
	errors: number,
	replaces: number,
	/**  Rows left out because their security is not in the book. */
	skipped: number,
};

/**  One line of the file, checked. */
export type PriceImportRow = {
	/**  Line in the file (1-based). */
	line: number,
	/**  The security as written in the file. */
	label: string,
	security: SecurityId | null,
	date: string | null,
	price: string | null,
	/**  A price is already stored for this date and will be replaced. */
	replaces: boolean,
	/**  The security is not in the book: the row is left out. */
	skipped: boolean,
	/**  Why the row cannot be imported. */
	error: string | null,
};

/**  One closing price (PRC-010). */
export type PricePoint = {
	security: SecurityId,
	date: string,
	price: string,
	source: PriceSource,
};

/**  Where a price came from (PRC-010 … PRC-040). */
export type PriceSource = "manual" | "csv" | "qif" | "download";

/**  One realized gain or loss. */
export type RealizedGain = {
	txn_id: TxnId,
	account: AccountId,
	security: SecurityId,
	security_label: string,
	/**
	 *  `None` for return of capital beyond basis (LOT-130), which has no
	 *  lot record.
	 */
	lot: LotId | null,
	sale_date: string,
	acquired: string | null,
	quantity: string | null,
	proceeds: string,
	basis: string,
	gain: string,
	/**  `None` for return of capital beyond basis. */
	term: Term | null,
	/**
	 *  From a taxable account; gains in tax-deferred and tax-exempt
	 *  accounts are kept but left out of taxable totals (LOT-160).
	 */
	taxable: boolean,
};

/**  Where a reconciliation stands. */
export type ReconStatus = "in_progress" | "finished" | "abandoned";

/**  A stored reconciliation. */
export type Reconciliation = {
	id: ReconciliationId,
	account: AccountId,
	statement_date: string,
	/**
	 *  The prior statement's ending balance when the session started
	 *  (RCN-030); the reconciled postings' total if there was none.
	 */
	opening_balance: string,
	/**  Ending balance on the statement, statement sign. */
	statement_balance: string,
	status: ReconStatus,
	started_at: string,
	finished_at: string | null,
};

/**  Row ID of a reconciliation. */
export type ReconciliationId = number;

/**
 *  A repeating pattern. Field use by frequency:
 * 
 *  | frequency | fields |
 *  |---|---|
 *  | once | `start_date` |
 *  | daily, weekly, monthly_last_day, yearly | `interval` |
 *  | twice_monthly | `day1`, `day2` (`day1 < day2`) |
 *  | monthly | `day1`, `interval` |
 *  | monthly_nth_weekday | `weekday` (1 = Monday … 7 = Sunday), `week_of_month` (1–4, or −1 = last), `interval` |
 * 
 *  Weekly repeats on `start_date`'s weekday; yearly on its month and day.
 */
export type Recurrence = {
	frequency: Frequency,
	interval: number,
	day1: number | null,
	day2: number | null,
	weekday: number | null,
	week_of_month: number | null,
	start_date: string,
	weekend_rule: WeekendRule,
};

/**  A page of register rows. */
export type RegisterPage = {
	rows: RegisterRow[],
	/**  Rows matching the filters, before `limit` and `offset`. */
	total: number,
	/**  The clock's today, for the today line (REG-070). */
	today: string,
};

/**
 *  Which register rows to show (REG-040). Every filter that is set must
 *  match.
 */
export type RegisterQuery = {
	account: AccountId,
	date_from: string | null,
	date_to: string | null,
	payee: PayeeId | null,
	/**  A category and its subcategories, on any line of the transaction. */
	category: CategoryId | null,
	tag: TagId | null,
	/**  This account's cleared status. */
	cleared: Cleared | null,
	/**
	 *  Case-insensitive text found in the payee, memo, notes, check
	 *  number, line memos, or category.
	 */
	text: string | null,
	sort: RegisterSort,
	descending: boolean,
	/**  Page size; `None` returns every matching row. */
	limit: number | null,
	offset: number,
};

/**  One row of an account register (REG-010, REG-020). */
export type RegisterRow = {
	txn_id: TxnId,
	date: string,
	check_num: string,
	payee: PayeeId | null,
	payee_name: string,
	memo: string,
	status: TxnStatus,
	/**  This account's posting. */
	amount: string,
	cleared: Cleared,
	counterpart: Counterpart,
	/**
	 *  What the Category column shows: a category path, `[Account]` for a
	 *  transfer, `--Split--` (REG-050), or empty.
	 */
	category: string,
	/**
	 *  Names of the tags on the transaction's postings, comma-separated
	 *  (TAG-010); empty when none.
	 */
	tags: string,
	/**
	 *  Running balance through this row in date order, whatever the
	 *  filter or sort (REG-020).
	 */
	balance: string,
	/**  Dated after today (REG-070). */
	future: boolean,
};

/**
 *  Register columns that can be sorted (REG-040). Ties break by date, then
 *  entry order.
 */
export type RegisterSort = "date" | "check_num" | "payee" | "amount" | "category" | "memo" | "cleared" | "balance";

/**  Register footer figures (REG-060). */
export type RegisterSummary = {
	/**  Postings dated today or earlier. */
	current: string,
	/**  Cleared and reconciled postings, any date. */
	cleared: string,
	/**  All postings, including future-dated ones (REG-070). */
	ending: string,
	/**
	 *  Credit cards with a limit: limit + current balance (the balance is
	 *  negative while money is owed).
	 */
	available_credit: string | null,
};

/**  What was generated. */
export type SampleSummary = {
	accounts: number,
	categories: number,
	payees: number,
	txns: number,
};

/**  A stored schedule. */
export type Schedule = {
	id: ScheduleId,
	fields: ScheduleFields,
	/**  Nominal date of the next occurrence; `None` once ended or deleted. */
	next_due: string | null,
	status: ScheduleStatus,
	created_at: string,
};

/**  Everything the user sets on a schedule (REC-010). */
export type ScheduleFields = {
	/**  The account whose register the transaction goes in. */
	account: AccountId,
	payee: PayeeId | null,
	memo: string,
	amount_type: AmountType,
	/**  At least one. One line is a simple transaction. */
	lines: ScheduleLine[],
	recurrence: Recurrence,
	end: End,
	/**  Days before the due date it shows in the due list. */
	remind_days: number,
	mode: EntryMode,
};

/**  Row ID of a schedule. */
export type ScheduleId = number;

/**  One line of the other side of a scheduled transaction (REC-150). */
export type ScheduleLine = {
	/**  A category, or the other account of a transfer. */
	target: Target,
	/**  Same sign as the schedule's amount, like an entry line. */
	amount: string,
	memo: string,
	tag: TagId | null,
};

/**  A row of the Scheduled Transactions list (REC-300). */
export type ScheduleRow = {
	schedule: Schedule,
	/**  "How often" text. */
	how_often: string,
	amount: string,
	/**  Next due date, weekend rule applied. */
	due_date: string | null,
	/**  "# left" for an after-count schedule. */
	left: number | null,
};

/**  Where a schedule stands. */
export type ScheduleStatus = "active" | 
/**  Ran out of occurrences (end date passed or "# left" reached 0). */
"ended" | "deleted";

/**
 *  One match: a transaction as one account's register shows it. A
 *  transfer matches once in each account it touches.
 */
export type SearchHit = {
	txn_id: TxnId,
	/**  The register that shows this row. */
	account: AccountId,
	date: string,
	payee_name: string,
	memo: string,
	status: TxnStatus,
	/**  This account's posting. */
	amount: string,
	/**  As the register's Category column shows it. */
	category: string,
};

export type SearchPage = {
	rows: SearchHit[],
	/**  All matches, before `limit`. */
	total: number,
};

/**  A search across accounts (UI-conventions: navigation bar search). */
export type SearchQuery = {
	/**
	 *  Case-insensitive text found in the payee, memo, notes, check
	 *  number, line memos, or category (a transfer's `[Account]` too);
	 *  or an amount ("184.23", "1,000"), which matches any line of the
	 *  transaction. Blank finds nothing.
	 */
	text: string,
	/**  Only this account's postings; `None` searches every account. */
	account: AccountId | null,
	/**  Most rows to return, newest first. */
	limit: number,
};

/**  A stored security. */
export type Security = {
	id: SecurityId,
	created_at: string,
} & SecurityFields;

/**  Editable attributes of a security (SEC-010 … SEC-030). */
export type SecurityFields = {
	name: string,
	/**  Unique when present; CDs and some bonds have none. */
	ticker: string | null,
	security_type: SecurityType,
	asset_class: AssetClass,
	/**  Nine characters (SEC-020). */
	cusip: string | null,
	/**  Overrides the account's default lot selection (SEC-030, LOT-100). */
	default_lot_method: LotMethod | null,
	/**  Hidden securities stay in history but leave pick lists (SEC-040). */
	hidden: boolean,
	notes: string,
};

/**  Row ID of a security. */
export type SecurityId = number;

/**  Kind of security (SEC-010). */
export type SecurityType = "stock" | "etf" | "mutual_fund" | "bond" | "money_market" | "cd" | "other";

export type SeedPreview = {
	/**  The date the Shares Added transactions get. */
	date: string,
	rows: SeedRow[],
	totals: SeedTotal[],
	good: number,
	errors: number,
};

/**  One line of the file, checked. */
export type SeedRow = {
	line: number,
	account_label: string,
	account: AccountId | null,
	security_label: string,
	security: SecurityId | null,
	acquired: string | null,
	quantity: string | null,
	basis: string | null,
	error: string | null,
};

/**  Lots, shares, and basis per account and security (MIG-050 totals). */
export type SeedTotal = {
	account: AccountId,
	security: SecurityId,
	lots: number,
	quantity: string,
	basis: string,
};

/**  An in-progress reconciliation, worked out for display (RCN-020 step 3). */
export type Session = {
	reconciliation: Reconciliation,
	/**
	 *  Items dated up to the statement date, oldest first: payments
	 *  (money out of an asset; charges on a credit card) and deposits
	 *  (money in; payments and credits on a credit card).
	 */
	payments: Item[],
	deposits: Item[],
	/**  Σ reconciled postings now. */
	opening: string,
	checked_payments: string,
	checked_payment_count: number,
	checked_deposits: string,
	checked_deposit_count: number,
	/**  `opening + checked payments + checked deposits`. */
	cleared_balance: string,
	/**  `statement balance − cleared balance`. Zero lets the user finish. */
	difference: string,
	opening_check: OpeningCheck,
};

/**  A split ratio: `new` shares for every `old` (2:1 is new 2, old 1). */
export type SplitRatio = {
	new: number,
	old: number,
};

/**  What starting a reconciliation needs (RCN-020 step 1). */
export type StartInput = {
	account: AccountId,
	statement_date: string,
	/**
	 *  Statement sign, as printed: a credit card balance owed is
	 *  positive.
	 */
	statement_balance: string,
	interest: StatementItem | null,
	service_charge: StatementItem | null,
};

/**
 *  Interest earned or a service charge from the statement, entered as a
 *  transaction when the session starts (RCN-020).
 */
export type StatementItem = {
	/**  On or before the statement date. */
	date: string,
	/**
	 *  Size of the item, greater than zero. The engine picks the sign:
	 *  interest raises an asset account and is a charge on a liability;
	 *  a service charge lowers either.
	 */
	amount: string,
	category: CategoryId,
};

/**  Built-in categories seeded by migration 0001 (CAT-060, RCN-040). */
export type SystemCategory = "dividends" | "interest" | "cg_dist_short" | "cg_dist_long" | "realized_gain" | "investment_income" | "investment_fees" | "investment_expense" | "tax_withheld" | "balance_adjustment" | "opening_balance";

/**  A stored tag. */
export type Tag = {
	id: TagId,
	created_at: string,
} & TagFields;

/**  Editable attributes of a tag. */
export type TagFields = {
	name: string,
	hidden: boolean,
};

/**  Row ID of a tag. */
export type TagId = number;

/**  What a posting is to. */
export type Target = { kind: "account"; id: AccountId } | { kind: "category"; id: CategoryId };

/**  Tax treatment (ACCT-030). */
export type TaxTreatment = "taxable" | "tax_deferred" | "tax_exempt";

/**  Holding period (LOT-040): one year or less is short. */
export type Term = "short" | "long";

/**  A stored transaction with its postings in line order. */
export type Txn = {
	id: TxnId,
	date: string,
	payee: PayeeId | null,
	check_num: string,
	memo: string,
	notes: string,
	status: TxnStatus,
	source: TxnSource,
	created_at: string,
	postings: Posting[],
};

/**  Row ID of a transaction. Immutable (TXN-070). */
export type TxnId = number;

/**  Where a transaction came from (TXN-070, REC-160, MIG-080). */
export type TxnSource = { kind: "manual" } | { kind: "import"; batch: number } | { kind: "schedule"; schedule: number } | { kind: "reconcile" } | { kind: "system" };

/**  Normal or voided (TXN-040). */
export type TxnStatus = "normal" | "void";

/**  What to do when a due date falls on a weekend (REC-050). */
export type WeekendRule = "none" | "previous" | "next";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

